-- 코드를 입력하세요
SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_OUTS AO LEFT JOIN ANIMAL_INS AI ON (AO.ANIMAL_ID = AI.ANIMAL_ID)
WHERE (
        SEX_UPON_OUTCOME LIKE 'Spayed%'
        OR SEX_UPON_OUTCOME LIKE 'Neutered%')
    AND (
        SEX_UPON_INTAKE LIKE 'Intact%')