-- 코드를 입력하세요
SELECT NAME, DATETIME
FROM(
    SELECT AI.NAME, AI.DATETIME
    FROM ANIMAL_INS AI LEFT JOIN ANIMAL_OUTS AO ON (AI.ANIMAL_ID = AO.ANIMAL_ID)
    WHERE AO.DATETIME IS NULL
    ORDER BY AI.DATETIME
    )
WHERE ROWNUM <= 3