-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FO.AMOUNT*FP.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER FO INNER JOIN FOOD_PRODUCT FP ON (FP.PRODUCT_ID=FO.PRODUCT_ID)
WHERE FO.PRODUCE_DATE BETWEEN DATE '2022-05-01' AND DATE '2022-05-31' 
GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID