SELECT H.HOUR, NVL(COUNT(A.DATETIME), 0) AS COUNT
FROM (
        SELECT LEVEL-1 AS HOUR 
        FROM DUAL 
        CONNECT BY LEVEL <= 24
    ) H
    LEFT JOIN ANIMAL_OUTS A ON (H.HOUR = TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24')))
GROUP BY H.HOUR
ORDER BY H.HOUR