WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(*) AS cnt
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
MAX_REVIEW AS (
    SELECT MEMBER_ID, cnt
    FROM REVIEW_COUNT
    WHERE cnt = (SELECT MAX(cnt) FROM REVIEW_COUNT)
    AND ROWNUM = 1
)
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, TO_CHAR(RR.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE MP 
    INNER JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
    INNER JOIN MAX_REVIEW MR ON RR.MEMBER_ID = MR.MEMBER_ID
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT;