-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON (C.CAR_ID = H.CAR_ID)
WHERE START_DATE BETWEEN DATE '2022-10-01' AND DATE '2022-10-31' AND CAR_TYPE = '세단'
GROUP BY C.CAR_ID
HAVING COUNT(C.CAR_ID) >= 1
ORDER BY C.CAR_ID DESC